spring.application.name=backend

spring.datasource.url=jdbc:postgresql://dpg-d7iilhm7r5hc73bivmq0-a:5432/auramusic
spring.datasource.username=admin
spring.datasource.password=83R3k5XxWpsm2TVsrW7P38SI5HffpJuX
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desactivar temporalmente la seguridad para poder probar el código
# (La activaremos más adelante cuando hagamos el Login)
spring.security.user.name=admin
spring.security.user.password=admin


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=auramusic.appags@gmail.com
spring.mail.password=hvwy zrbw lbjo gara
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true